/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as ThoughtsRouteRouteImport } from './routes/thoughts/route'
import { Route as OssRouteRouteImport } from './routes/oss/route'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as AwesomeListRouteRouteImport } from './routes/awesome-list/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OssIndexRouteImport } from './routes/oss/index'
import { Route as Blog1RouteImport } from './routes/blog/1'
import { Route as AwesomeListTvIndexRouteImport } from './routes/awesome-list/tv/index'
import { Route as AwesomeListMovieIndexRouteImport } from './routes/awesome-list/movie/index'
import { Route as AwesomeListBooksIndexRouteImport } from './routes/awesome-list/books/index'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const ThoughtsRouteRoute = ThoughtsRouteRouteImport.update({
  id: '/thoughts',
  path: '/thoughts',
  getParentRoute: () => rootRouteImport,
} as any)
const OssRouteRoute = OssRouteRouteImport.update({
  id: '/oss',
  path: '/oss',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AwesomeListRouteRoute = AwesomeListRouteRouteImport.update({
  id: '/awesome-list',
  path: '/awesome-list',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OssIndexRoute = OssIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OssRouteRoute,
} as any)
const Blog1Route = Blog1RouteImport.update({
  id: '/1',
  path: '/1',
  getParentRoute: () => BlogRouteRoute,
} as any)
const AwesomeListTvIndexRoute = AwesomeListTvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => AwesomeListRouteRoute,
} as any)
const AwesomeListMovieIndexRoute = AwesomeListMovieIndexRouteImport.update({
  id: '/movie/',
  path: '/movie/',
  getParentRoute: () => AwesomeListRouteRoute,
} as any)
const AwesomeListBooksIndexRoute = AwesomeListBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AwesomeListRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/awesome-list': typeof AwesomeListRouteRouteWithChildren
  '/blog': typeof BlogRouteRouteWithChildren
  '/oss': typeof OssRouteRouteWithChildren
  '/thoughts': typeof ThoughtsRouteRoute
  '/redirect': typeof RedirectRoute
  '/blog/1': typeof Blog1Route
  '/oss/': typeof OssIndexRoute
  '/awesome-list/books': typeof AwesomeListBooksIndexRoute
  '/awesome-list/movie': typeof AwesomeListMovieIndexRoute
  '/awesome-list/tv': typeof AwesomeListTvIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awesome-list': typeof AwesomeListRouteRouteWithChildren
  '/blog': typeof BlogRouteRouteWithChildren
  '/thoughts': typeof ThoughtsRouteRoute
  '/redirect': typeof RedirectRoute
  '/blog/1': typeof Blog1Route
  '/oss': typeof OssIndexRoute
  '/awesome-list/books': typeof AwesomeListBooksIndexRoute
  '/awesome-list/movie': typeof AwesomeListMovieIndexRoute
  '/awesome-list/tv': typeof AwesomeListTvIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/awesome-list': typeof AwesomeListRouteRouteWithChildren
  '/blog': typeof BlogRouteRouteWithChildren
  '/oss': typeof OssRouteRouteWithChildren
  '/thoughts': typeof ThoughtsRouteRoute
  '/redirect': typeof RedirectRoute
  '/blog/1': typeof Blog1Route
  '/oss/': typeof OssIndexRoute
  '/awesome-list/books/': typeof AwesomeListBooksIndexRoute
  '/awesome-list/movie/': typeof AwesomeListMovieIndexRoute
  '/awesome-list/tv/': typeof AwesomeListTvIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/awesome-list'
    | '/blog'
    | '/oss'
    | '/thoughts'
    | '/redirect'
    | '/blog/1'
    | '/oss/'
    | '/awesome-list/books'
    | '/awesome-list/movie'
    | '/awesome-list/tv'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awesome-list'
    | '/blog'
    | '/thoughts'
    | '/redirect'
    | '/blog/1'
    | '/oss'
    | '/awesome-list/books'
    | '/awesome-list/movie'
    | '/awesome-list/tv'
  id:
    | '__root__'
    | '/'
    | '/awesome-list'
    | '/blog'
    | '/oss'
    | '/thoughts'
    | '/redirect'
    | '/blog/1'
    | '/oss/'
    | '/awesome-list/books/'
    | '/awesome-list/movie/'
    | '/awesome-list/tv/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AwesomeListRouteRoute: typeof AwesomeListRouteRouteWithChildren
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  OssRouteRoute: typeof OssRouteRouteWithChildren
  ThoughtsRouteRoute: typeof ThoughtsRouteRoute
  RedirectRoute: typeof RedirectRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thoughts': {
      id: '/thoughts'
      path: '/thoughts'
      fullPath: '/thoughts'
      preLoaderRoute: typeof ThoughtsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oss': {
      id: '/oss'
      path: '/oss'
      fullPath: '/oss'
      preLoaderRoute: typeof OssRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awesome-list': {
      id: '/awesome-list'
      path: '/awesome-list'
      fullPath: '/awesome-list'
      preLoaderRoute: typeof AwesomeListRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oss/': {
      id: '/oss/'
      path: '/'
      fullPath: '/oss/'
      preLoaderRoute: typeof OssIndexRouteImport
      parentRoute: typeof OssRouteRoute
    }
    '/blog/1': {
      id: '/blog/1'
      path: '/1'
      fullPath: '/blog/1'
      preLoaderRoute: typeof Blog1RouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/awesome-list/tv/': {
      id: '/awesome-list/tv/'
      path: '/tv'
      fullPath: '/awesome-list/tv'
      preLoaderRoute: typeof AwesomeListTvIndexRouteImport
      parentRoute: typeof AwesomeListRouteRoute
    }
    '/awesome-list/movie/': {
      id: '/awesome-list/movie/'
      path: '/movie'
      fullPath: '/awesome-list/movie'
      preLoaderRoute: typeof AwesomeListMovieIndexRouteImport
      parentRoute: typeof AwesomeListRouteRoute
    }
    '/awesome-list/books/': {
      id: '/awesome-list/books/'
      path: '/books'
      fullPath: '/awesome-list/books'
      preLoaderRoute: typeof AwesomeListBooksIndexRouteImport
      parentRoute: typeof AwesomeListRouteRoute
    }
  }
}

interface AwesomeListRouteRouteChildren {
  AwesomeListBooksIndexRoute: typeof AwesomeListBooksIndexRoute
  AwesomeListMovieIndexRoute: typeof AwesomeListMovieIndexRoute
  AwesomeListTvIndexRoute: typeof AwesomeListTvIndexRoute
}

const AwesomeListRouteRouteChildren: AwesomeListRouteRouteChildren = {
  AwesomeListBooksIndexRoute: AwesomeListBooksIndexRoute,
  AwesomeListMovieIndexRoute: AwesomeListMovieIndexRoute,
  AwesomeListTvIndexRoute: AwesomeListTvIndexRoute,
}

const AwesomeListRouteRouteWithChildren =
  AwesomeListRouteRoute._addFileChildren(AwesomeListRouteRouteChildren)

interface BlogRouteRouteChildren {
  Blog1Route: typeof Blog1Route
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  Blog1Route: Blog1Route,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

interface OssRouteRouteChildren {
  OssIndexRoute: typeof OssIndexRoute
}

const OssRouteRouteChildren: OssRouteRouteChildren = {
  OssIndexRoute: OssIndexRoute,
}

const OssRouteRouteWithChildren = OssRouteRoute._addFileChildren(
  OssRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AwesomeListRouteRoute: AwesomeListRouteRouteWithChildren,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  OssRouteRoute: OssRouteRouteWithChildren,
  ThoughtsRouteRoute: ThoughtsRouteRoute,
  RedirectRoute: RedirectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
