/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as WritingRouteRouteImport } from './routes/writing/route'
import { Route as OssRouteRouteImport } from './routes/oss/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing/index'
import { Route as OssIndexRouteImport } from './routes/oss/index'
import { Route as WritingSlugRouteImport } from './routes/writing/$slug'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingRouteRoute = WritingRouteRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const OssRouteRoute = OssRouteRouteImport.update({
  id: '/oss',
  path: '/oss',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WritingRouteRoute,
} as any)
const OssIndexRoute = OssIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OssRouteRoute,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WritingRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oss': typeof OssRouteRouteWithChildren
  '/writing': typeof WritingRouteRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/oss/': typeof OssIndexRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/redirect': typeof RedirectRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/oss': typeof OssIndexRoute
  '/writing': typeof WritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oss': typeof OssRouteRouteWithChildren
  '/writing': typeof WritingRouteRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/oss/': typeof OssIndexRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/oss'
    | '/writing'
    | '/redirect'
    | '/writing/$slug'
    | '/oss/'
    | '/writing/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/redirect' | '/writing/$slug' | '/oss' | '/writing'
  id:
    | '__root__'
    | '/'
    | '/oss'
    | '/writing'
    | '/redirect'
    | '/writing/$slug'
    | '/oss/'
    | '/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OssRouteRoute: typeof OssRouteRouteWithChildren
  WritingRouteRoute: typeof WritingRouteRouteWithChildren
  RedirectRoute: typeof RedirectRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oss': {
      id: '/oss'
      path: '/oss'
      fullPath: '/oss'
      preLoaderRoute: typeof OssRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof WritingRouteRoute
    }
    '/oss/': {
      id: '/oss/'
      path: '/'
      fullPath: '/oss/'
      preLoaderRoute: typeof OssIndexRouteImport
      parentRoute: typeof OssRouteRoute
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof WritingRouteRoute
    }
  }
}

interface OssRouteRouteChildren {
  OssIndexRoute: typeof OssIndexRoute
}

const OssRouteRouteChildren: OssRouteRouteChildren = {
  OssIndexRoute: OssIndexRoute,
}

const OssRouteRouteWithChildren = OssRouteRoute._addFileChildren(
  OssRouteRouteChildren,
)

interface WritingRouteRouteChildren {
  WritingSlugRoute: typeof WritingSlugRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

const WritingRouteRouteChildren: WritingRouteRouteChildren = {
  WritingSlugRoute: WritingSlugRoute,
  WritingIndexRoute: WritingIndexRoute,
}

const WritingRouteRouteWithChildren = WritingRouteRoute._addFileChildren(
  WritingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OssRouteRoute: OssRouteRouteWithChildren,
  WritingRouteRoute: WritingRouteRouteWithChildren,
  RedirectRoute: RedirectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
