/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Blog1RouteImport } from './routes/blog/1'
import { Route as BlogThoughtsIndexRouteImport } from './routes/blog/thoughts/index'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Blog1Route = Blog1RouteImport.update({
  id: '/1',
  path: '/1',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogThoughtsIndexRoute = BlogThoughtsIndexRouteImport.update({
  id: '/thoughts/',
  path: '/thoughts/',
  getParentRoute: () => BlogRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/blog/1': typeof Blog1Route
  '/blog/thoughts': typeof BlogThoughtsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/blog/1': typeof Blog1Route
  '/blog/thoughts': typeof BlogThoughtsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/blog/1': typeof Blog1Route
  '/blog/thoughts/': typeof BlogThoughtsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog' | '/redirect' | '/blog/1' | '/blog/thoughts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/redirect' | '/blog/1' | '/blog/thoughts'
  id: '__root__' | '/' | '/blog' | '/redirect' | '/blog/1' | '/blog/thoughts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  RedirectRoute: typeof RedirectRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/1': {
      id: '/blog/1'
      path: '/1'
      fullPath: '/blog/1'
      preLoaderRoute: typeof Blog1RouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/thoughts/': {
      id: '/blog/thoughts/'
      path: '/thoughts'
      fullPath: '/blog/thoughts'
      preLoaderRoute: typeof BlogThoughtsIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
  }
}

interface BlogRouteRouteChildren {
  Blog1Route: typeof Blog1Route
  BlogThoughtsIndexRoute: typeof BlogThoughtsIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  Blog1Route: Blog1Route,
  BlogThoughtsIndexRoute: BlogThoughtsIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  RedirectRoute: RedirectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
